exclude:
  - 'node_modules/**'
  - 'dist/**'

linters:
  IdSelector:
    exclude: 'src/css/cs/items/_mainheader.scss'
  ImportantRule:
    enabled: false
  NameFormat:
    allow_leading_underscore: false
  NestingDepth:
    max_depth: 7
  SelectorDepth:
    enabled: false
  SelectorFormat:
    class_convention: ^(uc\-|ps(_|-)|psc_|PSForm)[a-zA-Z0-9\-_]*$
    exclude:
      - 'src/css/cs/items/_mainheader.scss'
      - 'src/css/cs/items/_selfservice.scss'
  StringQuotes:
    enabled: false
  QualifyingElement:
    enabled: false
  UrlFormat:
    enabled: false
